import fs from "node:fs";
import path from "node:path";
import * as sass from "sass";
import postcss from "postcss";
import postcssModules from "postcss-modules";
import Watcher from "watcher";

const SRC_DIR = "./src";
const OUT_CSS = "./astal-style.css";

const getPlugins = (tsFileName) => [
	postcssModules({
		generateScopedName: "[name]__[local]___[hash:base64:5]",
		getJSON: (_cssFileName, json) => {
			const content = `const styles = ${JSON.stringify(
				json,
				null,
				4,
			)};\nexport default styles;`;
			fs.writeFileSync(tsFileName, content);
		},
	}),
];

async function processFile(filePath) {
	if (path.basename(filePath).startsWith("_")) return;

	const tsFileName =
		filePath.substring(0, filePath.length - "module.scss".length) + "style.ts";

	try {
		const result = sass.compile(filePath, { loadPaths: [SRC_DIR] });

		const { css } = await postcss(getPlugins(tsFileName)).process(result.css, {
			from: filePath,
		});

		return css;
	} catch (e) {
		console.error(`Error processing ${filePath}:`, e.message);
		return "";
	}
}

async function buildAll() {
	console.log("Compiling CSS Modules...");
	const files = fs
		.readdirSync(SRC_DIR, { recursive: true })
		.map((f) => path.join(SRC_DIR, f));

	let globalCss = "/* Generated by styles.js */\n";

	for (const file of files) {
		if (file.endsWith(".module.scss")) {
			const css = await processFile(file);
			globalCss += css + "\n";
		} else if (file.endsWith(".style.ts")) {
			const scssFile =
				file.substring(0, file.length - "style.ts".length) + "module.scss";
			if (!files.includes(scssFile)) {
				try {
					fs.rmSync(file);
				} catch {}
			}
		}
	}

	if (fs.existsSync("./src/style.scss")) {
		try {
			const globalResult = sass.compile("./src/style.scss");
			globalCss += globalResult.css;
		} catch (e) {
			console.error("Global SCSS error:", e.message);
		}
	}

	fs.writeFileSync(OUT_CSS, globalCss);
	console.log(`Styles updated at ${OUT_CSS}`);
}

const watcher = new Watcher(`src`, {
	recursive: true,
	ignoreInitial: true,
});

watcher.on("all", (_eventName, path) => {
	if (path.toLowerCase().endsWith(".style.ts")) {
		return;
	}
	buildAll();
});

buildAll();
